services:
  web:
    container_name: web
    restart: unless-stopped
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"

  api:
    build: ./backend
    container_name: api
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////data/hackaton.db
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - api-data:/data

volumes:
  api-data:
